"""Behavioral tests for the migrated settings module.

Each test pins one Pydantic v1 -> v2 breaking-change site. The field names,
default values, and observable behavior must be preserved across the migration.
Do not edit this file — the verifier compares it against a pristine copy.
"""

import warnings

import pytest

from settings import AppSettings, settings_as_dict, settings_from_mapping


def test_defaults():
    s = AppSettings()
    assert s.host == "localhost"
    assert s.port == 8080
    assert s.log_level == "INFO"
    assert s.allowed_hosts == []
    assert s.workers == 4


def test_field_validator_rejects_bad_port():
    # The @validator("port") range check must still fire.
    with pytest.raises(Exception):
        AppSettings(port=70000)


def test_field_validator_accepts_good_port():
    assert AppSettings(port=9090).port == 9090


def test_pre_validator_splits_csv_list():
    # The pre=True validator must split a CSV string into a list.
    s = AppSettings(allowed_hosts="a.example, b.example ,c.example")
    assert s.allowed_hosts == ["a.example", "b.example", "c.example"]


def test_root_validator_cross_field_default():
    # replica_port defaults to port via the cross-field validator.
    assert AppSettings(port=5555).replica_port == 5555
    # ...but an explicit replica_port is preserved.
    assert AppSettings(port=5555, replica_port=6666).replica_port == 6666


def test_env_binding_for_aliased_field(monkeypatch):
    # log_level was Field(env="APP_LOG_LEVEL") in v1; the env binding must
    # survive the migration to v2 (validation_alias / settings config).
    monkeypatch.setenv("APP_LOG_LEVEL", "DEBUG")
    assert AppSettings().log_level == "DEBUG"


def test_env_binding_for_aliased_list(monkeypatch):
    monkeypatch.setenv("APP_ALLOWED_HOSTS", "x.example,y.example")
    assert AppSettings().allowed_hosts == ["x.example", "y.example"]


def test_model_dump_helper():
    # settings_as_dict used .dict() in v1 -> must be .model_dump() in v2.
    # .dict() still "works" in v2 but emits a PydanticDeprecatedSince20 warning;
    # treat that warning as an error so leaving the v1 call un-migrated fails.
    with warnings.catch_warnings():
        warnings.simplefilter("error", DeprecationWarning)
        d = settings_as_dict(AppSettings(port=8081))
    assert isinstance(d, dict)
    assert d["port"] == 8081
    assert d["host"] == "localhost"


def test_model_validate_helper():
    # settings_from_mapping used .parse_obj() in v1 -> .model_validate() in v2.
    # .parse_obj() is likewise deprecated-but-working; treat the warning as error.
    with warnings.catch_warnings():
        warnings.simplefilter("error", DeprecationWarning)
        s = settings_from_mapping({"host": "h", "port": 1234})
    assert s.host == "h"
    assert s.port == 1234
